name: CI

on: [push, pull_request]
jobs:
  test_glibc_llvm:
    name: "Test with clang/glibc/libc++/lld on Arch Linux"
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - run: pacman --noconfirm --noprogressbar -Syyu
    - run: pacman --noconfirm --noprogressbar -Sy git clang lld libc++ pkgconf meson ninja wayland wayland-protocols libinput libxkbcommon pixman glm libdrm libglvnd cairo
    - uses: actions/checkout@v1
    - run: git submodule sync --recursive && git submodule update --init --force --recursive
    - run: env CC=clang CXX=clang++ CXXFLAGS="-stdlib=libc++" LDFLAGS="-fuse-ld=lld -stdlib=libc++" meson build
    - run: ninja -v -Cbuild
