name: CI

on: [push, pull_request]
jobs:
  test_code_style:
    name: "Check code style with uncrustify"
    runs-on: ubuntu-latest
    steps:
        - run: sudo apt-get update
        - run: sudo apt-get install -y git cmake gcc make
        - uses: actions/checkout@v1
        - run: git clone http://github.com/ammen99/uncrustify
        - run: cd uncrustify && mkdir build && cd build && cmake ../ && make && cd ../../
        - run: ls -la
        - run: git ls-files | grep "hpp$\|cpp$" | xargs ./uncrustify/build/uncrustify -c uncrustify.ini --check -f
