name: CI

on: [push, pull_request]
jobs:
  test_code_style:
    name: "Check code style with uncrustify"
    runs-on: ubuntu-latest
    steps:
        - run: sudo apt-get update
        - run: sudo apt-get install -y git cmake gcc make
        - run: git clone http://github.com/ammen99/uncrustify
        - run: cd uncrustify && mkdir build && cd build && cmake ../ && make && export PATH=$PATH:$(pwd) && cd ../../
        - uses: actions/checkout@v1
        - git ls-files | grep "hpp$\|cpp" | xargs uncrustify -c uncrustify.ini --check -f
